[project]
name = "Helpers"
version = "0.1.0"
description = "Personal Helpers"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fire>=0.6.0",
    "pathspec>=0.12.1",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.0.1",
]
